### ISSUE TITLE
Feature request: Compatibility with Duckling

### ISSUE THREAD

**Issue by Not-February** [team-abnormals/incubation#14]
It'd be great if it were possible for ducks(or really any other modded critter that lays eggs in a way similar to chickens), to use the nests of Incubation like chickens do.

I don't know how feasible that is, though, so failing that, I am here to request compatibility with the [Duckling](https://www.curseforge.com/minecraft/mc-mods/duckling) mod.

**Comment by bageldotjpg** [comment]
Unfortunately, no plans for this at the moment. Someone is welcome to make a compatibility add-on, though.
