### ISSUE TITLE
egg crates can't be used as fuellllll

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/incubation#15]
quark blah

**Comment by bageldotjpg** [comment]
Not adding compat for this because its dumb

**Comment by thelegitdolt** [comment]
bro what is the point of adding compat if you're not gonna make it consistent

**Comment by thelegitdolt** [comment]
https://github.com/team-abnormals/endergetic/commit/4ee1b392673a6f10281ef1fea68572ffd9ebe564 also you might want to revert this if that's the case

**Comment by bageldotjpg** [comment]
1) egg crates aren't even quark compat
2) makes more sense for fruits, not EGGS

**Comment by thelegitdolt** [comment]
> egg crates aren't even quark compat

Yo what i didn't know this. 

> makes more sense for fruits, not EGGS

ok fair but like. i tested in a craetive world and they're all flammable so
