### ISSUE TITLE
Issue with TaxVillageArchitect Mod

### ISSUE THREAD

**Issue by DragonGirl7567** [team-abnormals/incubation#23]
The game crashed whilst mouseclicked event handler
Error: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:TaxVillageArchitect+M.1.20.1+ForM.1.1.0.jar

version: 1.20.1

Blueprint                      -       blueprint-1.20.1-7.0.3.jar
Incubation                    -      incubation-1.20.1-4.0.0.jar
Tax' Village Architect    -      TaxVillageArchitect+M.1.20.1+ForM.1.1.0.jar

(will send a notice to tax's mod too)

**Comment by bageldotjpg** [comment]
Nothing I can do about it, closed source mod and that bug seems very odd and seems like their fault
They claim to have fixed it here though: https://www.curseforge.com/minecraft/mc-mods/taxvillagearchitect/comments
