### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by IsLegitimate** [team-abnormals/incubation#26]
Causes a Exit 1 crash when starting up

**Comment by EarthboundRune** [comment]
still doing it despite saying fixed

**Comment by bageldotjpg** [comment]
Make sure the following are true:
- Incubation is on 4.0.2
- Blueprint is on 7.1.0
- (if installed) Autumnity is on 5.0.2

If everything is updated and still not fixed, reopen with a crash log provided
