### ISSUE TITLE
Incubation has a false value for blueprint version

### ISSUE THREAD

**Issue by IsLegitimate** [team-abnormals/incubation#27]
**This is the error in the log:** [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'blueprint', Requested by: 'incubation', Expected range: '[7.1.0,)', Actual version: '7.0.3'
	
The Latest version of Blueprint on curseforge is 1.20.1 is 7.0.3... I looked for a version 7.1.0 I found it on modrinth not curseforge.

I guess just add an updated version to the list for 1.20.1 on curseforge

Thanks Cheers.

**Comment by bageldotjpg** [comment]
7.1.0 exists, download it off modrinth for now

It has been uploaded on curseforge for about 14 hours now but Curse flagged it for manual review so it will be available when they approve it
