### ISSUE TITLE
would it be possible to upgrade to 1.16.5?

### ISSUE THREAD

**Issue by Monalisa2232** [team-abnormals/incubation#7]
it would be super cool to be able to play this mod in my world, but it only has for 1.16.1. would it be possible to make it available for 1.16.5?

**Comment by bageldotjpg** [comment]
The mods features are available on 1.16.5 in the form of [Environmental](https://www.curseforge.com/minecraft/mc-mods/environmental). But, we will not be backporting or working on any releases on the 1.16.5 version anymore.
